
from machina.machina import Machina
import os

prompt_reviewr = Machina(api_key=os.getenv("GEMINI_API_KEY"), model="gemini-1.5-flash",
                        prompt="""
Given the system’s original prompt, user input, system output, and user ratings, refine the system prompt to improve the quality and relevance of future responses.

Input Format:
	1.	System Prompt: The original instruction provided to the AI.
	2.	User Input: The specific query or request from the user.
	3.	System Output: The response generated by the AI.
	4.	User Feedback: User feedback on the output (e.g., numerical score, qualitative feedback).

Expected Output:

An enhanced version of the System Prompt that incorporates insights from the input data to improve future AI responses.

Process:
	1.	Analyze Ratings & Feedback:
	•	If the rating is high, keep the core structure of the prompt but refine it for clarity and precision.
	•	If the rating is low, identify weaknesses in the AI response and adjust the prompt accordingly.
	2.	Identify Gaps in the System Output:
	•	Did the output fully address the user input?
	•	Was it too generic, too complex, or missing key details?
	•	Did it misinterpret the intent of the query?
	3.	Refine the System Prompt:
	•	Adjust wording to clarify expectations.
	•	Specify additional constraints or guidelines for better accuracy.
	•	Incorporate examples or formatting improvements.
	•	Ensure the prompt guides the AI toward generating responses that align with user needs.

Example Enhancement:

Input:
	•	System Prompt: “Answer the user’s question concisely.”
	•	User Input: “How does quantum computing work?”
	•	System Output: “Quantum computing uses qubits and superposition to perform calculations faster than classical computers.”
	•	User feedback: 3/5 “Too vague, please explain in more detail.”

Enhanced System Prompt:
“Provide a clear and structured explanation of the user’s question. Ensure responses are concise yet informative, with relevant examples or analogies. Avoid being too vague. For technical topics, break down complex concepts into digestible explanations.”
                        """,
                        )

ret = prompt_reviewr.ask(f"""
    System Prompt: {prompt_reviewr.system_prompt}
    User Input: {prompt_reviewr.user_input}
    System Output: {prompt_reviewr.system_output}
    Rating: {prompt_reviewr.rating}
""")
print(ret.parts[0].text)